### ISSUE TITLE
Salutation

### ISSUE THREAD

**Issue by YingqinSU** [uvsq22000841/projet_snake#1]
je viens de voir votre code.

ptdr le code de Salah XD
bon, t'as raison, il y a que toi qui commit en fait
en vrai je me suis bien amusé, mon record est 38 x)

J'ai remarqué qu'il y a des trucs que vous avez pas besoin de mettre, par exemple 
    - ligne 40, tu peux faire : score, game, vitesse = 0, False, 200
    - ligne 63, pas besoin de global speed, t'as pas changé dans la fonction
    - ligne 75, idem pour vitesse

Sur ce, bon courage pour la suite.

**Comment by SalahHarnoufi** [comment]
mdr ouais haha, ba écoute merci du conseil, mais en vrai je préfère laisser les variables globales comme ça, ça fait un peu plus aéerer, et pour les 2 autres oue c'est vrai j'ai pas fait gaffe,

merci toi aussi.
